name: Build and Deploy AsciiDoc to GitHub Pages

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install Asciidoctor
      run: |
        gem install asciidoctor
        gem install asciidoctor-diagram
        
    - name: Build Documentation
      run: |
        mkdir -p site
        # Copy assets first
        cp -r images site/ 2>/dev/null || echo "No images directory found"
        cp -r styles site/ 2>/dev/null || echo "No styles directory found"
        # Build HTML
        asciidoctor \
          --destination-dir site \
          --out-file index.html \
          --attribute toc=left \
          --attribute toclevels=3 \
          --attribute sectlinks \
          --attribute sectanchors \
          --attribute sectnums \
          --attribute icons=font \
          --attribute source-highlighter=highlight.js \
          index.adoc
          
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4